services:
    perl:
        image: ghcr.io/kan/docker-perl-cpm/perl-cpm:5.30.1
        volumes:
            - ./:/app
            - perl-local:/app/local
        environment:
            PERL5LIB: /app/local/lib/perl5
            PATH: /app/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        tty: true
volumes:
  perl-local:
    driver: local
